### ISSUE TITLE
Crash when trying to start with Forge 

### ISSUE THREAD

**Issue by Heavy4** [Energy0124/MCFreedomLauncher#22]
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LightWayUp** [comment]
@Heavy4 I tried looking in Forge's repository, but couldn't find net.minecraft.launchwrapper.Launch.class. I'll try to reproduce the error when I get back home later today.

When does this happen, when installing Forge, starting launcher, or trying to play?

**Comment by sladki7** [comment]
when starting game with forge version (.json file in .minecraft/version/ )

**Comment by LightWayUp** [comment]
This issue is reproducible with the latest official launcher ( .minecraft/ folder was deleted before testing started ). Forge seems to be incompatible with Java 9, and they'll need to fix it. As software is updated ( and it's updated for a reason ), developers should also have their code accommodate to it. Such huge project as Forge needs time to update, so I'll work on a workaround. Please expect a commit be pushed tomorrow.

**Comment by sladki7** [comment]
are you alive?

**Comment by LightWayUp** [comment]
I'm sorry about the delay. There are multiple projects I'm working on currently, and I had to rebuild my development environment because my OS was corrupted and I had to reinstall and setup everything again. If everything goes well, I should be able to push a commit before next weekend.

**Comment by LightWayUp** [comment]
Please see https://github.com/Mojang/LegacyLauncher/pull/11 for more information regarding the compatibility of LegacyLauncher which Forge and OptiFine use.

**Comment by LightWayUp** [comment]
@sladki7 This should be fixed in the next minor release (2.01.00), although it could take some time to come.

**Comment by sladki7** [comment]
all is well?

**Comment by LightWayUp** [comment]
I'm sorry for the huge delay. Originally I planned to simply push an commit that drops the target level back to Java 8, but the current branch contains quite some issues and I hope to address those altogether. The next update will have updated launcher (1.6.84-j) and authlib (1.5.25) source, plus numerous fixes, many new under-the-hood features, better documentation and greatly improved general code quality.

**Comment by LightWayUp** [comment]
Sorry, again, for the extremely long delay. I'm currently refactoring some code to make it cleaner and more optimized. A good news is that the half-finished code does compile now, so it shouldn't be too far away to the very first alpha release.
