### ISSUE TITLE
Forge doesnt work

### ISSUE THREAD

**Issue by sladki7** [Energy0124/MCFreedomLauncher#24]
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LightWayUp** [comment]
Please see https://github.com/Energy0124/MCFreedomLauncher/issues/22.
